language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    matrix:
        - PLATFORMIO_CI_SRC=examples/test_ublox_gps

install:
    - pip install -U platformio
    - pio update

script:
    - platformio ci --lib="./src" --project-conf platformio.ini
